services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db_local
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recme
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local_db_network

volumes:
  postgres_data_local:

networks:
  local_db_network:
    name: local_db_network
    driver: bridge
